# Generated by Django 4.0 on 2022-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
